### ISSUE TITLE
Change landing page to index.html, dashboard page to a different html file name

### ISSUE THREAD

**Issue by ShepLT1** [ShepLT1/covid-tracker#42]
We will want the landing page code inside index.html so that it displays when the user visits the site. The covid19 dashboard page (currently in index.html) will need to be named as a different html file. I can start linking the landing page state clicks to the covid19 dashboard once this pathway is set

**Comment by Robeil** [comment]
I renamed the file landing.html to index.html

**Comment by GAFelton** [comment]
index.html *(formerly landing.html)* now in root folder, along with dashboard.html *(formerly index.html)*.
